logging:
  level:
    org:
      springframework: INFO
      apache: INFO
    com:
      alibaba: ERROR
      nickel:
        medicalrecord: DEBUG
spring:
  datasource:
    url: jdbc:mysql://192.168.21.134:3306/medical_record?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 数据库连接池最大连接数
      max-active: 10
      # 启动连接池时，初始建立的连接数量
      initial-size: 0
      # 数据库连接池最小连接数
      min-idle: 1
      # 数据库连接池等待连接返回的最大等待时间
      max-wait: 5000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
